#!python
Import('env')

r = {
    'libs' : [],
    'path' : [],
    'objs' : []
}

src = env.FindFiles('./', '*.c')
src = env.FindFiles('./', '*.cpp')
objs = env.SourceToObjects(src)

Depends(objs, env['CPPINCLUDES'])
r['objs'].extend(objs)
Return('r')
