#!python
Import('env')

r = {
    'libs' : [],
    'path' : [],
    'objs' : []
}

src = env.FindFiles('./', '*.c')
src.extend(env.FindFiles('./', '*.cpp'))
objs = env.Object(src)

Depends(objs, env['CPPINCLUDES'])
r['objs'].extend(objs)

Return('r')
